handlers = java.util.logging.FileHandler

.level = INFO

java.util.logging.FileHandler.pattern = logs/finbro.log
java.util.logging.FileHandler.append = true
java.util.logging.FileHandler.formatter = seedu.finbro.utils.LogFormatter
