@startuml
'https://plantuml.com/sequence-diagram

->":Ui"++: "limit 100"
deactivate ":Ui"
":Ui" -> ":Finbro"++: input = "limit 100"

":Finbro" -> ":Parser" ++: parse(input)

create "c:SetLimitCommand"
":Parser" -> "c:SetLimitCommand"++: new SetLimitCommand(input)
return c
return c

":Finbro" -> "c:SetLimitCommand"++: execute(...)
"c:SetLimitCommand" -> "c:SetLimitCommand"++: verifyLimitType(input)
return limit: double
"c:SetLimitCommand" -> "c:SetLimitCommand"++: verifyLimitRange(limit)
return

"c:SetLimitCommand" -> "c:SetLimitCommand"++: confirmLimitChange(limit)
"c:SetLimitCommand" ->":Ui"++: readCommand()
return confirmMessage

alt confirmMessage == "yes"
    "c:SetLimitCommand" -> ":Limit"++: setLimit(limit)
    return
else confirmMessage == "no"
else invalid confirmMessage
end
return

"c:SetLimitCommand" -> ":Ui"++ : showLimit()
return
return

":Finbro" -> "storage:Storage"++ :save()
"storage:Storage" -> ":Limit"++: toFileFormat()
return
return
deactivate

@enduml
