@startuml
'https://plantuml.com/sequence-diagram

participant ":Ui" as ui
participant "c:SetLimitCommand" as c

-> c++: execute(...)

c -> c++: verify user input
return
c -> c++: confirmLimitChange(limit)
c ->ui++: readCommand()
return confirmMessage

alt confirmMessage == "yes"
    c -> ":Limit"++: setLimit(limit)
    return
else confirmMessage == "no"
else invalid confirmMessage
end
return

c -> ui++ : showLimit()
return
return

@enduml
