@startuml ViewCommand
'https://plantuml.com/sequence-diagram
actor User

participant ":Finbro"
participant ":Ui"
participant ":Parser"
participant "c:ViewCommand"
participant ":ExpenseList"


activate ":Finbro"
":Finbro" -> ":Ui" ++ : readCommand()
User -> ":Ui" : "view (argument)"
":Ui" --> ":Finbro" : input
deactivate ":Ui"

":Finbro" -> ":Parser" : parse(input)
activate ":Parser"


create "c:ViewCommand"
":Parser" -> "c:ViewCommand" : new ViewCommand(argument)
activate "c:ViewCommand"
return c
return c

":Finbro" -> "c:ViewCommand" : execute(...)
activate "c:ViewCommand"

alt view all
    "c:ViewCommand" -> ":ExpenseList" : getAll()
    activate ":ExpenseList"
    return expenses
    "c:ViewCommand" -> ":Ui" : showAllExpenses(expenses)
    activate ":Ui"
    ":Ui" -> User : display expenses
    return

else view <category>
    "c:ViewCommand" -> ":ExpenseList" : getCategoryExpenses(arg)
    activate ":ExpenseList"
    return expenses
    "c:ViewCommand" -> ":Ui" : showAllExpenses(expenses)
    activate ":Ui"
    ":Ui" -> User : display expenses
    return

else invalid
    "c:ViewCommand" -> ":Finbro" : throw FinbroException
    ":Finbro" -> ":Ui" : showError(...)
    activate ":Ui"
    ":Ui" -> User : error message
    return
end

deactivate "c:ViewCommand"
deactivate ":Finbro"
deactivate ":Ui"

@enduml
